controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix: /api
api_login_check: 
    path: /api/login_check
    methods: [POST]



# authentication_token:
#     path: /authentication_token
