controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix: /api
authentication_token:
    path: /authentication_token

# api_login_check: /api/login_check